
services:
  db:
    image: mysql:9.2.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: paynest
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306